name = "worker-rust"
main = "build/worker/shim.mjs"

[build]
command = "cargo install -q worker-build && worker-build --release"

[durable_objects]
bindings = [
  { name = "ULTIMATUM2023", class_name = "Ultimatum2023" },
  { name = "USER", class_name = "User" },
]
