[advisories]
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]
vulnerability = "deny"
unmaintained = "deny"
yanked = "deny"
notice = "deny"
ignore = []

[licenses]
unlicensed = "deny"
copyleft = "deny"
allow = [
    "MIT",
    "MIT-0",
    "Apache-2.0",
    "BSD-3-Clause",
    "ISC",
    "Zlib",
    "0BSD",
    "BSD-2-Clause",
    "CC0-1.0",
    "BSL-1.0",
]
default = "deny"

[bans]
multiple-versions = "deny"
wildcards = "deny"
highlight = "all"
skip = []

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
