[package]
name = "eagle-client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eagle-game = { workspace = true }
eagle-types = { workspace = true }
