[package]
name = "eagle-game"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eagle-types = { workspace = true }

bevy_reflect = "0.10"
serde = "1.0"
